apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: k8s-taloria-com-tls
spec:
  secretName: k8s-taloria-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: k8s.taloria.com
  dnsNames:
    - k8s.taloria.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - k8s.taloria.com