---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
      - name: server
        image: thetalorian/md-server
        #resources:
        #  limits:
        #    memory: "128Mi"
        #    cpu: "500m"
        ports:
        - containerPort: 5000
        env:
          - name: REDIS_HOST
            value: redis-clusterip-service
          - name: REDIS_PORT
            value: '6379'
          - name: PGUSER
            value: postgres
          - name: PGHOST
            value: postgres-clusterip-service
          - name: PGPORT
            value: '5432'
          - name: PGDATABASE
            value: postgres
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: pgpassword
                key: PGPASSWORD

